export const WORD_SETS = [
  {
    id: 'classic',
    name: 'Classic',
    description: 'Simple opposites',
    pairs: [
      ['HOT', 'COLD'],
      ['BIG', 'SMALL'],
      ['FAST', 'SLOW'],
      ['LIGHT', 'DARK'],
      ['HAPPY', 'SAD'],
      ['OPEN', 'CLOSE'],
      ['FULL', 'EMPTY'],
      ['CLEAN', 'DIRTY'],
    ],
  },
  {
    id: 'emotions',
    name: 'Feelings',
    description: 'Common feelings',
    pairs: [
      ['HAPPY', 'SAD'],
      ['CALM', 'ANGRY'],
      ['PROUD', 'SHY'],
      ['BRAVE', 'AFRAID'],
      ['TIRED', 'AWAKE'],
      ['KIND', 'MEAN'],
      ['HOPE', 'WORRY'],
      ['TRUST', 'DOUBT'],
    ],
  },
  {
    id: 'landscapes',
    name: 'Landscapes',
    description: 'Places outside',
    pairs: [
      ['HILL', 'VALLEY'],
      ['RIVER', 'LAKE'],
      ['BEACH', 'ISLAND'],
      ['FOREST', 'FIELD'],
      ['DESERT', 'OCEAN'],
      ['MOUNTAIN', 'PLAIN'],
      ['CAVE', 'CLIFF'],
      ['PATH', 'ROAD'],
    ],
  },
  {
    id: 'weather',
    name: 'Weather',
    description: 'Sky and seasons',
    pairs: [
      ['RAIN', 'SUN'],
      ['WIND', 'CLOUD'],
      ['SNOW', 'ICE'],
      ['STORM', 'FOG'],
      ['HOT', 'COLD'],
      ['WARM', 'COOL'],
      ['DRY', 'WET'],
      ['THUNDER', 'LIGHT'],
    ],
  },
  {
    id: 'home',
    name: 'Home',
    description: 'Household nouns',
    pairs: [
      ['TABLE', 'CHAIR'],
      ['DOOR', 'WINDOW'],
      ['BED', 'SOFA'],
      ['FLOOR', 'WALL'],
      ['KITCHEN', 'BATH'],
      ['CUP', 'PLATE'],
      ['SPOON', 'FORK'],
      ['LAMP', 'CLOCK'],
    ],
  },
  {
    id: 'school',
    name: 'School',
    description: 'Classroom words',
    pairs: [
      ['BOOK', 'PEN'],
      ['DESK', 'BOARD'],
      ['TEACHER', 'STUDENT'],
      ['LESSON', 'TEST'],
      ['READ', 'WRITE'],
      ['LISTEN', 'SPEAK'],
      ['PAPER', 'PENCIL'],
      ['CLASS', 'BREAK'],
    ],
  },
  {
    id: 'food',
    name: 'Food',
    description: 'Everyday food',
    pairs: [
      ['BREAD', 'RICE'],
      ['APPLE', 'BANANA'],
      ['WATER', 'MILK'],
      ['SOUP', 'SALAD'],
      ['EGG', 'CHEESE'],
      ['FISH', 'MEAT'],
      ['SUGAR', 'SALT'],
      ['FRUIT', 'CAKE'],
    ],
  },
  {
    id: 'actions',
    name: 'Actions',
    description: 'Common verbs',
    pairs: [
      ['EAT', 'DRINK'],
      ['READ', 'WRITE'],
      ['OPEN', 'CLOSE'],
      ['SIT', 'STAND'],
      ['WALK', 'RUN'],
      ['GIVE', 'TAKE'],
      ['PUSH', 'PULL'],
      ['BUY', 'SELL'],
    ],
  },
  {
    id: 'nature',
    name: 'Nature',
    description: 'Animals and plants',
    pairs: [
      ['TREE', 'FLOWER'],
      ['GRASS', 'LEAF'],
      ['BIRD', 'FISH'],
      ['HORSE', 'SHEEP'],
      ['CAT', 'DOG'],
      ['SEED', 'ROOT'],
      ['ROCK', 'SAND'],
      ['SKY', 'SEA'],
    ],
  },
  {
    id: 'strategy',
    name: 'Strategy',
    description: 'Duel tactics',
    pairs: [
      ['ATTACK', 'DEFEND'],
      ['RISK', 'SAFETY'],
      ['CHAOS', 'ORDER'],
      ['FOCUS', 'DISTRACT'],
      ['ADVANCE', 'RETREAT'],
      ['POWER', 'SHIELD'],
      ['WIN', 'LOSE'],
      ['TRAP', 'ESCAPE'],
    ],
  },
  {
    id: 'abstract',
    name: 'Abstract',
    description: 'Bigger ideas',
    pairs: [
      ['TRUTH', 'FICTION'],
      ['LOGIC', 'INSTINCT'],
      ['MEMORY', 'FORGET'],
      ['FREEDOM', 'CONTROL'],
      ['ORIGIN', 'ENDING'],
      ['REASON', 'DREAM'],
      ['CHANGE', 'STAY'],
      ['CHOICE', 'RULE'],
    ],
  },
  {
    id: 'crush',
    name: 'Crush',
    description: 'Arcade energy',
    pairs: [
      ['CRUSH', 'REVIVE'],
      ['SPARK', 'SHADOW'],
      ['BURST', 'SETTLE'],
      ['CLASH', 'HARMONY'],
      ['POWER', 'FRAGILE'],
      ['BOOST', 'BLOCK'],
      ['FLASH', 'FREEZE'],
      ['COMBO', 'BONUS'],
    ],
  },
] as const;

export const WORD_MEANINGS: Record<string, string> = {
  HOT: 'very warm',
  COLD: 'not warm',
  BIG: 'large in size',
  SMALL: 'little in size',
  FAST: 'moves quickly',
  SLOW: 'not fast',
  LIGHT: 'bright, not dark',
  DARK: 'with little light',
  HAPPY: 'feeling good',
  SAD: 'feeling unhappy',
  OPEN: 'not closed',
  CLOSE: 'shut something',
  FULL: 'has no empty space',
  EMPTY: 'has nothing inside',
  CLEAN: 'not dirty',
  DIRTY: 'not clean',
  CALM: 'quiet and relaxed',
  ANGRY: 'very upset',
  PROUD: 'happy about yourself',
  SHY: 'quiet with people',
  BRAVE: 'not afraid',
  AFRAID: 'feeling fear',
  TIRED: 'needs rest',
  AWAKE: 'not sleeping',
  KIND: 'nice to others',
  MEAN: 'not nice',
  HOPE: 'want good things',
  WORRY: 'think about problems',
  TRUST: 'believe someone',
  DOUBT: 'not feel sure',
  HILL: 'small mountain',
  VALLEY: 'low land between hills',
  RIVER: 'water that moves',
  LAKE: 'water with land around it',
  BEACH: 'sand near water',
  ISLAND: 'land with water around it',
  FOREST: 'many trees together',
  FIELD: 'open land',
  DESERT: 'very dry land',
  OCEAN: 'very big sea',
  MOUNTAIN: 'very high land',
  PLAIN: 'flat open land',
  CAVE: 'hole in a rock',
  CLIFF: 'high steep rock',
  PATH: 'small way to walk',
  ROAD: 'way for cars',
  RAIN: 'water from clouds',
  SUN: 'bright star in the sky',
  WIND: 'moving air',
  CLOUD: 'white or gray sky shape',
  SNOW: 'cold white flakes',
  ICE: 'frozen water',
  STORM: 'bad weather',
  FOG: 'cloud near the ground',
  WARM: 'a little hot',
  COOL: 'a little cold',
  DRY: 'not wet',
  WET: 'has water on it',
  THUNDER: 'loud storm sound',
  TABLE: 'furniture for eating',
  CHAIR: 'seat for one person',
  DOOR: 'opens into a room',
  WINDOW: 'glass in a wall',
  BED: 'place to sleep',
  SOFA: 'soft seat for people',
  FLOOR: 'bottom of a room',
  WALL: 'side of a room',
  KITCHEN: 'room for cooking',
  BATH: 'place to wash',
  CUP: 'small thing for drinking',
  PLATE: 'dish for food',
  SPOON: 'tool for eating soup',
  FORK: 'tool for eating food',
  LAMP: 'gives light',
  CLOCK: 'shows the time',
  BOOK: 'pages to read',
  PEN: 'tool for writing',
  DESK: 'table for school work',
  BOARD: 'teacher writes on it',
  TEACHER: 'person who teaches',
  STUDENT: 'person who learns',
  LESSON: 'time for learning',
  TEST: 'questions to answer',
  READ: 'look at words',
  WRITE: 'make words on paper',
  LISTEN: 'hear carefully',
  SPEAK: 'say words',
  PAPER: 'thin white sheet',
  PENCIL: 'tool for writing',
  CLASS: 'group learning together',
  BREAK: 'short rest time',
  BREAD: 'food from flour',
  RICE: 'small white food grains',
  APPLE: 'round fruit',
  BANANA: 'long yellow fruit',
  WATER: 'clear drink',
  MILK: 'white drink',
  SOUP: 'hot liquid food',
  SALAD: 'cold vegetables',
  EGG: 'food from a chicken',
  CHEESE: 'food from milk',
  FISH: 'animal that swims',
  MEAT: 'food from animals',
  SUGAR: 'sweet white food',
  SALT: 'white food for taste',
  FRUIT: 'sweet food from plants',
  CAKE: 'sweet baked food',
  EAT: 'put food in your mouth',
  DRINK: 'take liquid in',
  SIT: 'be on a chair',
  STAND: 'be on your feet',
  WALK: 'move on foot',
  RUN: 'move very fast',
  GIVE: 'let someone have it',
  TAKE: 'get something',
  PUSH: 'move away from you',
  PULL: 'move toward you',
  BUY: 'get with money',
  SELL: 'give for money',
  TREE: 'tall plant',
  FLOWER: 'colorful plant part',
  GRASS: 'green plant on the ground',
  LEAF: 'green part of a plant',
  BIRD: 'animal with wings',
  HORSE: 'large animal to ride',
  SHEEP: 'animal with wool',
  CAT: 'small pet animal',
  DOG: 'friendly pet animal',
  SEED: 'small start of a plant',
  ROOT: 'plant part in the ground',
  ROCK: 'hard piece of stone',
  SAND: 'tiny pieces of rock',
  SKY: 'space above us',
  SEA: 'large salt water',
  ATTACK: 'try to hurt or win',
  DEFEND: 'keep safe',
  RISK: 'chance of danger',
  SAFETY: 'not in danger',
  CHAOS: 'no order',
  ORDER: 'things in the right place',
  FOCUS: 'pay attention',
  DISTRACT: 'take attention away',
  ADVANCE: 'move forward',
  RETREAT: 'move back',
  POWER: 'strong ability',
  SHIELD: 'thing that protects',
  WIN: 'be first or best',
  LOSE: 'not win',
  TRAP: 'thing that catches',
  ESCAPE: 'get away',
  TRUTH: 'what is real',
  FICTION: 'made-up story',
  LOGIC: 'clear thinking',
  INSTINCT: 'feeling without thinking',
  MEMORY: 'something you remember',
  FORGET: 'not remember',
  FREEDOM: 'able to choose',
  CONTROL: 'power to direct',
  ORIGIN: 'where something starts',
  ENDING: 'where something stops',
  REASON: 'why something happens',
  DREAM: 'pictures while sleeping',
  CHANGE: 'become different',
  STAY: 'not leave',
  CHOICE: 'thing you choose',
  RULE: 'what you must follow',
  CRUSH: 'press very hard',
  REVIVE: 'bring back',
  SPARK: 'small flash of fire',
  SHADOW: 'dark shape',
  BURST: 'break open quickly',
  SETTLE: 'become calm',
  CLASH: 'hit or fight',
  HARMONY: 'works well together',
  FRAGILE: 'breaks easily',
  BOOST: 'make stronger',
  BLOCK: 'stop the way',
  FLASH: 'quick bright light',
  FREEZE: 'become ice cold',
  COMBO: 'things working together',
  BONUS: 'extra prize',
};

export const MATCH_WORD_COUNT_OPTIONS = [10, 11, 12, 13, 14, 15, 16] as const;
export const DEFAULT_TOTAL_WORDS = 16;

export function normalizeWordCount(wordCount: number | null | undefined): number {
  if (!wordCount) return DEFAULT_TOTAL_WORDS;
  const available = [...MATCH_WORD_COUNT_OPTIONS] as number[];
  return available.includes(wordCount) ? wordCount : DEFAULT_TOTAL_WORDS;
}

export type WordSetId = (typeof WORD_SETS)[number]['id'];

export const DEFAULT_WORD_SET_ID: WordSetId = 'classic';

export const WORD_PAIRS = WORD_SETS[0].pairs;

export function getWordSet(wordSetId: string | null | undefined = DEFAULT_WORD_SET_ID) {
  return WORD_SETS.find((set) => set.id === wordSetId) ?? WORD_SETS[0];
}

export function getAllWords(wordSetId?: string | null): string[] {
  return getWordSet(wordSetId).pairs.flatMap(([a, b]) => [a, b]);
}

export function getGameWords(wordSetId?: string | null, wordCount?: number | null): string[] {
  return getAllWords(wordSetId).slice(0, normalizeWordCount(wordCount));
}

export function getInitialActiveWords(wordSetId?: string | null, wordCount?: number | null): [string, string] {
  const words = getGameWords(wordSetId, wordCount);
  return [words[0], words[1]];
}

export function getInitialUnusedWords(wordSetId?: string | null, wordCount?: number | null): string[] {
  const [first, second] = getInitialActiveWords(wordSetId, wordCount);
  return getGameWords(wordSetId, wordCount).filter((word) => word !== first && word !== second);
}

export function getWordMeaning(word: string | null | undefined): string | null {
  if (!word) return null;
  return WORD_MEANINGS[word.toUpperCase()] ?? null;
}
